extends: airbnb

env:
  jest: true

rules:
  quotes:
    - error
    - double
  linebreak-style: 0
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - "**/*.test.js"
      - "**/*.spec.js"
      - "contrib/**"
      - "test/**"
