image: node:8.12.0

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

stages:
  - install
  - build
  - test

npm_install:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build

lint:
  stage: build
  script:
    - npm run lint-md
    - npm run lint-json
    - npm run lint-yaml
    - npm run lint-js
    - npm run lint-tasks

test:
  stage: test
  script:
    - npm run-script coverage
  coverage: "/All files[^|]*\\|[^|]*\\s+([\\d\\.]+)/"
